[auth]
cookie_name = "bidding_prediction_app"
cookie_key = "K7mP9qS2tV5xZ8aC1dF4gH7jL0nR3uW6yB9eI2kN5pS8"
cookie_expiry_days = 30

[credentials.usernames.customer_a]
name = "顧客A"
password = "$2b$12$8K.mN2pQ5rS7tU1vW3xY6a2bC4dE7fG9hJ2kL5mN8pQrStUvWxYz01"

[credentials.usernames.customer_b]
name = "顧客B"
password = "$2b$12$3xY6zA2bC4dE7fG9hJ2kL5mN8pQ5rS7tU1vW3xY6zA2bC4dE7fG9h"

[credentials.usernames.admin]
name = "admin"
password = "$2b$12$5mN8pQ5rS7tU1vW3xY6zA2bC4dE7fG9hJ2kL5mN8pQ5rS7tU1vW3x"